name: Publish

on:
    push:
        tags: 
            - 'v*' # limited the triggering tags to tags starting with v like v0.0.1.
    workflow_dispatch:

env:
    CARGO_TERM_COLOR: always
    
jobs:
    publish_crates:
        name: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout sources
              uses: actions/checkout@v2
      
            - name: Install stable toolchain
              uses: actions-rs/toolchain@v1
              with:
                profile: minimal
                toolchain: stable
                override: true

            #- run: cargo publish --token ${CRATES_TOKEN}
            #  env:
            #    CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
            
            - uses: johnyherangi/create-release-notes@main
              id: create-release-notes
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Create release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: ${{ github.ref }}
                release_name: Release ${{ github.ref }}
                body: ${{ steps.create-release-notes.outputs.release-notes }}
                draft: false
                prerelease: true